# aUTOMAX
<VirtualHost *:80>
    ServerName automax.localhost
    DocumentRoot /var/www/html/automax

    <Directory /var/www/html/automax>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    php_value upload_max_filesize 8M
    php_value post_max_size 10M

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ /index.php [L]

    ErrorLog  ${APACHE_LOG_DIR}/automax-error.log
    CustomLog ${APACHE_LOG_DIR}/automax-access.log combined
</VirtualHost>

# flowgate
<VirtualHost *:8081>
    ServerName flowgate.localhost
    DocumentRoot /var/www/html/flowgate

    <Directory /var/www/html/flowgate>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ /index.php [L]

    ErrorLog  ${APACHE_LOG_DIR}/flowgate-error.log
    CustomLog ${APACHE_LOG_DIR}/flowgate-access.log combined
</VirtualHost>